### PR TITLE
Transformer support

### PR DESCRIPTION
**Pull request by RobinGeens**
Add extra support for ONNX operators in the graphs of transformer networks. This PR depends on the following:

- [x] The newest version of ZigZag: https://github.com/KULeuven-MICAS/zigzag/pull/65
- [x] The reformatting changes from https://github.com/KULeuven-MICAS/stream/pull/33 (to be merged)
- [x] ZigZag 3.6.1 (the package must still be uploaded!)

I have added the following features:

-  Correctly parse reshape, gather and transpose nodes, also with 4D tensors
-  Speedup the code by giving ComputationNode a static hash
-  Speedup the code by making the `tensor_cns` a full tensor of `object`s, instead of a tensor of sets
-  Various typehints
-  Wrap the DiGraph class with typehints

Regarding the speedup: I timed the simulation the OPT-125M model (~8 layers of 6M elements) with caching of ZigZag results. The execution time dropped from **19m44s** to **2min12s**

### CODE REVIEW

**Comment by RobinGeens** [comment]
profiling

**Comment by RobinGeens** [comment]
Related To do's:
[1](https://github.com/orgs/KULeuven-MICAS/projects/9/views/2?pane=issue&itemId=74579660)

**Comment by RobinGeens** [comment]
Resolves https://github.com/KULeuven-MICAS/stream/issues/38

**Review by asyms — APPROVED** [review]
Great success!

**Pull request merged**
